apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sparc
  namespace: default
stringData:
  SPARC_DB_HOST: db.example.edu
  SPARC_DB_NAME: sparc_db
  SPARC_DB_PASS: sparc-db_password
  SPARC_DB_USER: sparc_db_user
